# Generated by Django 3.1.6 on 2021-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='btc_count',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
