# Generated by Django 3.1.6 on 2021-02-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0002_auto_20210212_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='btc_count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
