# Generated by Django 3.1.6 on 2021-02-12 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0004_auto_20210212_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='btc_count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='range_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
