# Generated by Django 3.1.6 on 2021-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0005_auto_20210212_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='btc_count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='range_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
