# Generated by Django 3.1.6 on 2021-02-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0006_auto_20210213_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
