# Generated by Django 3.1.6 on 2021-02-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0007_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='range_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
    ]
