# Generated by Django 3.1.6 on 2021-02-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binanceApp', '0008_auto_20210215_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=None),
        ),
    ]
